//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cliente.ServicioJuego {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Partida", Namespace="http://schemas.datacontract.org/2004/07/AccesoDatos")]
    [System.SerializableAttribute()]
    public partial class Partida : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Cliente.ServicioJuego.DatosJugadorPartida[] DatosJugadorPartidaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codigoPartidaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> duracionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string estadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> fechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idPartidaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreGanadorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> puntajeVictoriaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> tiempoGuerraField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Cliente.ServicioJuego.DatosJugadorPartida[] DatosJugadorPartida {
            get {
                return this.DatosJugadorPartidaField;
            }
            set {
                if ((object.ReferenceEquals(this.DatosJugadorPartidaField, value) != true)) {
                    this.DatosJugadorPartidaField = value;
                    this.RaisePropertyChanged("DatosJugadorPartida");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string codigoPartida {
            get {
                return this.codigoPartidaField;
            }
            set {
                if ((object.ReferenceEquals(this.codigoPartidaField, value) != true)) {
                    this.codigoPartidaField = value;
                    this.RaisePropertyChanged("codigoPartida");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> duracion {
            get {
                return this.duracionField;
            }
            set {
                if ((this.duracionField.Equals(value) != true)) {
                    this.duracionField = value;
                    this.RaisePropertyChanged("duracion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string estado {
            get {
                return this.estadoField;
            }
            set {
                if ((object.ReferenceEquals(this.estadoField, value) != true)) {
                    this.estadoField = value;
                    this.RaisePropertyChanged("estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> fecha {
            get {
                return this.fechaField;
            }
            set {
                if ((this.fechaField.Equals(value) != true)) {
                    this.fechaField = value;
                    this.RaisePropertyChanged("fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idPartida {
            get {
                return this.idPartidaField;
            }
            set {
                if ((this.idPartidaField.Equals(value) != true)) {
                    this.idPartidaField = value;
                    this.RaisePropertyChanged("idPartida");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombreGanador {
            get {
                return this.nombreGanadorField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreGanadorField, value) != true)) {
                    this.nombreGanadorField = value;
                    this.RaisePropertyChanged("nombreGanador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> puntajeVictoria {
            get {
                return this.puntajeVictoriaField;
            }
            set {
                if ((this.puntajeVictoriaField.Equals(value) != true)) {
                    this.puntajeVictoriaField = value;
                    this.RaisePropertyChanged("puntajeVictoria");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> tiempoGuerra {
            get {
                return this.tiempoGuerraField;
            }
            set {
                if ((this.tiempoGuerraField.Equals(value) != true)) {
                    this.tiempoGuerraField = value;
                    this.RaisePropertyChanged("tiempoGuerra");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DatosJugadorPartida", Namespace="http://schemas.datacontract.org/2004/07/AccesoDatos")]
    [System.SerializableAttribute()]
    public partial class DatosJugadorPartida : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Cliente.ServicioJuego.Jugador JugadorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Cliente.ServicioJuego.Partida PartidaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string claveJugadorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codigoPartidaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> esAdminField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> expulsadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> idAspectoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idDatosJugadorPartidaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idJugadorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> idPartidaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> puntajeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Cliente.ServicioJuego.Jugador Jugador {
            get {
                return this.JugadorField;
            }
            set {
                if ((object.ReferenceEquals(this.JugadorField, value) != true)) {
                    this.JugadorField = value;
                    this.RaisePropertyChanged("Jugador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Cliente.ServicioJuego.Partida Partida {
            get {
                return this.PartidaField;
            }
            set {
                if ((object.ReferenceEquals(this.PartidaField, value) != true)) {
                    this.PartidaField = value;
                    this.RaisePropertyChanged("Partida");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string claveJugador {
            get {
                return this.claveJugadorField;
            }
            set {
                if ((object.ReferenceEquals(this.claveJugadorField, value) != true)) {
                    this.claveJugadorField = value;
                    this.RaisePropertyChanged("claveJugador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string codigoPartida {
            get {
                return this.codigoPartidaField;
            }
            set {
                if ((object.ReferenceEquals(this.codigoPartidaField, value) != true)) {
                    this.codigoPartidaField = value;
                    this.RaisePropertyChanged("codigoPartida");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> esAdmin {
            get {
                return this.esAdminField;
            }
            set {
                if ((this.esAdminField.Equals(value) != true)) {
                    this.esAdminField = value;
                    this.RaisePropertyChanged("esAdmin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> expulsado {
            get {
                return this.expulsadoField;
            }
            set {
                if ((this.expulsadoField.Equals(value) != true)) {
                    this.expulsadoField = value;
                    this.RaisePropertyChanged("expulsado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> idAspecto {
            get {
                return this.idAspectoField;
            }
            set {
                if ((this.idAspectoField.Equals(value) != true)) {
                    this.idAspectoField = value;
                    this.RaisePropertyChanged("idAspecto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idDatosJugadorPartida {
            get {
                return this.idDatosJugadorPartidaField;
            }
            set {
                if ((this.idDatosJugadorPartidaField.Equals(value) != true)) {
                    this.idDatosJugadorPartidaField = value;
                    this.RaisePropertyChanged("idDatosJugadorPartida");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idJugador {
            get {
                return this.idJugadorField;
            }
            set {
                if ((this.idJugadorField.Equals(value) != true)) {
                    this.idJugadorField = value;
                    this.RaisePropertyChanged("idJugador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> idPartida {
            get {
                return this.idPartidaField;
            }
            set {
                if ((this.idPartidaField.Equals(value) != true)) {
                    this.idPartidaField = value;
                    this.RaisePropertyChanged("idPartida");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> puntaje {
            get {
                return this.puntajeField;
            }
            set {
                if ((this.puntajeField.Equals(value) != true)) {
                    this.puntajeField = value;
                    this.RaisePropertyChanged("puntaje");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Jugador", Namespace="http://schemas.datacontract.org/2004/07/AccesoDatos")]
    [System.SerializableAttribute()]
    public partial class Jugador : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Cliente.ServicioJuego.DatosJugadorPartida[] DatosJugadorPartidaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Cliente.ServicioJuego.SolicitudAmigo[] SolicitudAmigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string claveUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string contraseniaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string correoElectronicoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> esInvitadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string estadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] fotoPerfilField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idJugadorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreUsuarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Cliente.ServicioJuego.DatosJugadorPartida[] DatosJugadorPartida {
            get {
                return this.DatosJugadorPartidaField;
            }
            set {
                if ((object.ReferenceEquals(this.DatosJugadorPartidaField, value) != true)) {
                    this.DatosJugadorPartidaField = value;
                    this.RaisePropertyChanged("DatosJugadorPartida");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Cliente.ServicioJuego.SolicitudAmigo[] SolicitudAmigo {
            get {
                return this.SolicitudAmigoField;
            }
            set {
                if ((object.ReferenceEquals(this.SolicitudAmigoField, value) != true)) {
                    this.SolicitudAmigoField = value;
                    this.RaisePropertyChanged("SolicitudAmigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string claveUsuario {
            get {
                return this.claveUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.claveUsuarioField, value) != true)) {
                    this.claveUsuarioField = value;
                    this.RaisePropertyChanged("claveUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string contrasenia {
            get {
                return this.contraseniaField;
            }
            set {
                if ((object.ReferenceEquals(this.contraseniaField, value) != true)) {
                    this.contraseniaField = value;
                    this.RaisePropertyChanged("contrasenia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string correoElectronico {
            get {
                return this.correoElectronicoField;
            }
            set {
                if ((object.ReferenceEquals(this.correoElectronicoField, value) != true)) {
                    this.correoElectronicoField = value;
                    this.RaisePropertyChanged("correoElectronico");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.descripcionField, value) != true)) {
                    this.descripcionField = value;
                    this.RaisePropertyChanged("descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> esInvitado {
            get {
                return this.esInvitadoField;
            }
            set {
                if ((this.esInvitadoField.Equals(value) != true)) {
                    this.esInvitadoField = value;
                    this.RaisePropertyChanged("esInvitado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string estado {
            get {
                return this.estadoField;
            }
            set {
                if ((object.ReferenceEquals(this.estadoField, value) != true)) {
                    this.estadoField = value;
                    this.RaisePropertyChanged("estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] fotoPerfil {
            get {
                return this.fotoPerfilField;
            }
            set {
                if ((object.ReferenceEquals(this.fotoPerfilField, value) != true)) {
                    this.fotoPerfilField = value;
                    this.RaisePropertyChanged("fotoPerfil");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idJugador {
            get {
                return this.idJugadorField;
            }
            set {
                if ((this.idJugadorField.Equals(value) != true)) {
                    this.idJugadorField = value;
                    this.RaisePropertyChanged("idJugador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombreUsuario {
            get {
                return this.nombreUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreUsuarioField, value) != true)) {
                    this.nombreUsuarioField = value;
                    this.RaisePropertyChanged("nombreUsuario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SolicitudAmigo", Namespace="http://schemas.datacontract.org/2004/07/AccesoDatos")]
    [System.SerializableAttribute()]
    public partial class SolicitudAmigo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Cliente.ServicioJuego.Amigo AmigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Cliente.ServicioJuego.Jugador JugadorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string estadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> fechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idAmigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idJugadorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idSolicitudAmigoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Cliente.ServicioJuego.Amigo Amigo {
            get {
                return this.AmigoField;
            }
            set {
                if ((object.ReferenceEquals(this.AmigoField, value) != true)) {
                    this.AmigoField = value;
                    this.RaisePropertyChanged("Amigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Cliente.ServicioJuego.Jugador Jugador {
            get {
                return this.JugadorField;
            }
            set {
                if ((object.ReferenceEquals(this.JugadorField, value) != true)) {
                    this.JugadorField = value;
                    this.RaisePropertyChanged("Jugador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string estado {
            get {
                return this.estadoField;
            }
            set {
                if ((object.ReferenceEquals(this.estadoField, value) != true)) {
                    this.estadoField = value;
                    this.RaisePropertyChanged("estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> fecha {
            get {
                return this.fechaField;
            }
            set {
                if ((this.fechaField.Equals(value) != true)) {
                    this.fechaField = value;
                    this.RaisePropertyChanged("fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idAmigo {
            get {
                return this.idAmigoField;
            }
            set {
                if ((this.idAmigoField.Equals(value) != true)) {
                    this.idAmigoField = value;
                    this.RaisePropertyChanged("idAmigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idJugador {
            get {
                return this.idJugadorField;
            }
            set {
                if ((this.idJugadorField.Equals(value) != true)) {
                    this.idJugadorField = value;
                    this.RaisePropertyChanged("idJugador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idSolicitudAmigo {
            get {
                return this.idSolicitudAmigoField;
            }
            set {
                if ((this.idSolicitudAmigoField.Equals(value) != true)) {
                    this.idSolicitudAmigoField = value;
                    this.RaisePropertyChanged("idSolicitudAmigo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Amigo", Namespace="http://schemas.datacontract.org/2004/07/AccesoDatos")]
    [System.SerializableAttribute()]
    public partial class Amigo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Cliente.ServicioJuego.SolicitudAmigo[] SolicitudAmigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string claveUsuarioAmigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idAmigoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Cliente.ServicioJuego.SolicitudAmigo[] SolicitudAmigo {
            get {
                return this.SolicitudAmigoField;
            }
            set {
                if ((object.ReferenceEquals(this.SolicitudAmigoField, value) != true)) {
                    this.SolicitudAmigoField = value;
                    this.RaisePropertyChanged("SolicitudAmigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string claveUsuarioAmigo {
            get {
                return this.claveUsuarioAmigoField;
            }
            set {
                if ((object.ReferenceEquals(this.claveUsuarioAmigoField, value) != true)) {
                    this.claveUsuarioAmigoField = value;
                    this.RaisePropertyChanged("claveUsuarioAmigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idAmigo {
            get {
                return this.idAmigoField;
            }
            set {
                if ((this.idAmigoField.Equals(value) != true)) {
                    this.idAmigoField = value;
                    this.RaisePropertyChanged("idAmigo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioJuego.IServicioJuego", CallbackContract=typeof(Cliente.ServicioJuego.IServicioJuegoCallback))]
    public interface IServicioJuego {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioJuego/CrearPartida", ReplyAction="http://tempuri.org/IServicioJuego/CrearPartidaResponse")]
        Cliente.ServicioJuego.Partida CrearPartida(string claveJugador, int idJugador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioJuego/CrearPartida", ReplyAction="http://tempuri.org/IServicioJuego/CrearPartidaResponse")]
        System.Threading.Tasks.Task<Cliente.ServicioJuego.Partida> CrearPartidaAsync(string claveJugador, int idJugador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioJuego/UnirsePartida", ReplyAction="http://tempuri.org/IServicioJuego/UnirsePartidaResponse")]
        bool UnirsePartida(string codigoPartida, int idJugador, string claveJugador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioJuego/UnirsePartida", ReplyAction="http://tempuri.org/IServicioJuego/UnirsePartidaResponse")]
        System.Threading.Tasks.Task<bool> UnirsePartidaAsync(string codigoPartida, int idJugador, string claveJugador);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServicioJuego/CambiarConfiguracionPartida")]
        void CambiarConfiguracionPartida(Cliente.ServicioJuego.Partida partidaLocal);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServicioJuego/CambiarConfiguracionPartida")]
        System.Threading.Tasks.Task CambiarConfiguracionPartidaAsync(Cliente.ServicioJuego.Partida partidaLocal);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServicioJuego/CambiarDatosJugador")]
        void CambiarDatosJugador(Cliente.ServicioJuego.DatosJugadorPartida datosLocales);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServicioJuego/CambiarDatosJugador")]
        System.Threading.Tasks.Task CambiarDatosJugadorAsync(Cliente.ServicioJuego.DatosJugadorPartida datosLocales);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioJuego/RetornarDatosJugador", ReplyAction="http://tempuri.org/IServicioJuego/RetornarDatosJugadorResponse")]
        Cliente.ServicioJuego.DatosJugadorPartida[] RetornarDatosJugador(string codigoPartida);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioJuego/RetornarDatosJugador", ReplyAction="http://tempuri.org/IServicioJuego/RetornarDatosJugadorResponse")]
        System.Threading.Tasks.Task<Cliente.ServicioJuego.DatosJugadorPartida[]> RetornarDatosJugadorAsync(string codigoPartida);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioJuego/RetornarPartida", ReplyAction="http://tempuri.org/IServicioJuego/RetornarPartidaResponse")]
        Cliente.ServicioJuego.Partida RetornarPartida(string codigoPartida);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioJuego/RetornarPartida", ReplyAction="http://tempuri.org/IServicioJuego/RetornarPartidaResponse")]
        System.Threading.Tasks.Task<Cliente.ServicioJuego.Partida> RetornarPartidaAsync(string codigoPartida);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServicioJuego/IniciarPartida")]
        void IniciarPartida(string codigoPartida);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServicioJuego/IniciarPartida")]
        System.Threading.Tasks.Task IniciarPartidaAsync(string codigoPartida);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServicioJuego/SalirPartida")]
        void SalirPartida(Cliente.ServicioJuego.DatosJugadorPartida datos, Cliente.ServicioJuego.Partida partidaLocal);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServicioJuego/SalirPartida")]
        System.Threading.Tasks.Task SalirPartidaAsync(Cliente.ServicioJuego.DatosJugadorPartida datos, Cliente.ServicioJuego.Partida partidaLocal);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioJuegoCallback {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioJuego/ActualizarPartida", ReplyAction="http://tempuri.org/IServicioJuego/ActualizarPartidaResponse")]
        void ActualizarPartida(Cliente.ServicioJuego.Partida partidaLocal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioJuego/ActualizarDatos", ReplyAction="http://tempuri.org/IServicioJuego/ActualizarDatosResponse")]
        void ActualizarDatos(Cliente.ServicioJuego.DatosJugadorPartida datos);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioJuegoChannel : Cliente.ServicioJuego.IServicioJuego, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioJuegoClient : System.ServiceModel.DuplexClientBase<Cliente.ServicioJuego.IServicioJuego>, Cliente.ServicioJuego.IServicioJuego {
        
        public ServicioJuegoClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public ServicioJuegoClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public ServicioJuegoClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioJuegoClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioJuegoClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public Cliente.ServicioJuego.Partida CrearPartida(string claveJugador, int idJugador) {
            return base.Channel.CrearPartida(claveJugador, idJugador);
        }
        
        public System.Threading.Tasks.Task<Cliente.ServicioJuego.Partida> CrearPartidaAsync(string claveJugador, int idJugador) {
            return base.Channel.CrearPartidaAsync(claveJugador, idJugador);
        }
        
        public bool UnirsePartida(string codigoPartida, int idJugador, string claveJugador) {
            return base.Channel.UnirsePartida(codigoPartida, idJugador, claveJugador);
        }
        
        public System.Threading.Tasks.Task<bool> UnirsePartidaAsync(string codigoPartida, int idJugador, string claveJugador) {
            return base.Channel.UnirsePartidaAsync(codigoPartida, idJugador, claveJugador);
        }
        
        public void CambiarConfiguracionPartida(Cliente.ServicioJuego.Partida partidaLocal) {
            base.Channel.CambiarConfiguracionPartida(partidaLocal);
        }
        
        public System.Threading.Tasks.Task CambiarConfiguracionPartidaAsync(Cliente.ServicioJuego.Partida partidaLocal) {
            return base.Channel.CambiarConfiguracionPartidaAsync(partidaLocal);
        }
        
        public void CambiarDatosJugador(Cliente.ServicioJuego.DatosJugadorPartida datosLocales) {
            base.Channel.CambiarDatosJugador(datosLocales);
        }
        
        public System.Threading.Tasks.Task CambiarDatosJugadorAsync(Cliente.ServicioJuego.DatosJugadorPartida datosLocales) {
            return base.Channel.CambiarDatosJugadorAsync(datosLocales);
        }
        
        public Cliente.ServicioJuego.DatosJugadorPartida[] RetornarDatosJugador(string codigoPartida) {
            return base.Channel.RetornarDatosJugador(codigoPartida);
        }
        
        public System.Threading.Tasks.Task<Cliente.ServicioJuego.DatosJugadorPartida[]> RetornarDatosJugadorAsync(string codigoPartida) {
            return base.Channel.RetornarDatosJugadorAsync(codigoPartida);
        }
        
        public Cliente.ServicioJuego.Partida RetornarPartida(string codigoPartida) {
            return base.Channel.RetornarPartida(codigoPartida);
        }
        
        public System.Threading.Tasks.Task<Cliente.ServicioJuego.Partida> RetornarPartidaAsync(string codigoPartida) {
            return base.Channel.RetornarPartidaAsync(codigoPartida);
        }
        
        public void IniciarPartida(string codigoPartida) {
            base.Channel.IniciarPartida(codigoPartida);
        }
        
        public System.Threading.Tasks.Task IniciarPartidaAsync(string codigoPartida) {
            return base.Channel.IniciarPartidaAsync(codigoPartida);
        }
        
        public void SalirPartida(Cliente.ServicioJuego.DatosJugadorPartida datos, Cliente.ServicioJuego.Partida partidaLocal) {
            base.Channel.SalirPartida(datos, partidaLocal);
        }
        
        public System.Threading.Tasks.Task SalirPartidaAsync(Cliente.ServicioJuego.DatosJugadorPartida datos, Cliente.ServicioJuego.Partida partidaLocal) {
            return base.Channel.SalirPartidaAsync(datos, partidaLocal);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioJuego.IServicioChat", CallbackContract=typeof(Cliente.ServicioJuego.IServicioChatCallback))]
    public interface IServicioChat {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServicioChat/Unirse")]
        void Unirse(string nombreUsuario);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServicioChat/Unirse")]
        System.Threading.Tasks.Task UnirseAsync(string nombreUsuario);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServicioChat/EnviarMensaje")]
        void EnviarMensaje(string nombreUsuario, string mensaje);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServicioChat/EnviarMensaje")]
        System.Threading.Tasks.Task EnviarMensajeAsync(string nombreUsuario, string mensaje);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioChat/ProbarConexion", ReplyAction="http://tempuri.org/IServicioChat/ProbarConexionResponse")]
        bool ProbarConexion();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioChat/ProbarConexion", ReplyAction="http://tempuri.org/IServicioChat/ProbarConexionResponse")]
        System.Threading.Tasks.Task<bool> ProbarConexionAsync();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServicioChat/Salir")]
        void Salir(string nombreUsuario);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServicioChat/Salir")]
        System.Threading.Tasks.Task SalirAsync(string nombreUsuario);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioChatCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServicioChat/RecibirMensaje")]
        void RecibirMensaje(string mensajeCompleto);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioChatChannel : Cliente.ServicioJuego.IServicioChat, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioChatClient : System.ServiceModel.DuplexClientBase<Cliente.ServicioJuego.IServicioChat>, Cliente.ServicioJuego.IServicioChat {
        
        public ServicioChatClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public ServicioChatClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public ServicioChatClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioChatClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioChatClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void Unirse(string nombreUsuario) {
            base.Channel.Unirse(nombreUsuario);
        }
        
        public System.Threading.Tasks.Task UnirseAsync(string nombreUsuario) {
            return base.Channel.UnirseAsync(nombreUsuario);
        }
        
        public void EnviarMensaje(string nombreUsuario, string mensaje) {
            base.Channel.EnviarMensaje(nombreUsuario, mensaje);
        }
        
        public System.Threading.Tasks.Task EnviarMensajeAsync(string nombreUsuario, string mensaje) {
            return base.Channel.EnviarMensajeAsync(nombreUsuario, mensaje);
        }
        
        public bool ProbarConexion() {
            return base.Channel.ProbarConexion();
        }
        
        public System.Threading.Tasks.Task<bool> ProbarConexionAsync() {
            return base.Channel.ProbarConexionAsync();
        }
        
        public void Salir(string nombreUsuario) {
            base.Channel.Salir(nombreUsuario);
        }
        
        public System.Threading.Tasks.Task SalirAsync(string nombreUsuario) {
            return base.Channel.SalirAsync(nombreUsuario);
        }
    }
}
