//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cliente.ServiciosGestionUsuarios {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Usuario", Namespace="http://schemas.datacontract.org/2004/07/Servicios.Interfaces")]
    [System.SerializableAttribute()]
    public partial class Usuario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContraseniaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CorreoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreUsuarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Contrasenia {
            get {
                return this.ContraseniaField;
            }
            set {
                if ((object.ReferenceEquals(this.ContraseniaField, value) != true)) {
                    this.ContraseniaField = value;
                    this.RaisePropertyChanged("Contrasenia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Correo {
            get {
                return this.CorreoField;
            }
            set {
                if ((object.ReferenceEquals(this.CorreoField, value) != true)) {
                    this.CorreoField = value;
                    this.RaisePropertyChanged("Correo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreUsuario {
            get {
                return this.NombreUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreUsuarioField, value) != true)) {
                    this.NombreUsuarioField = value;
                    this.RaisePropertyChanged("NombreUsuario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Jugador", Namespace="http://schemas.datacontract.org/2004/07/AccesoDatos")]
    [System.SerializableAttribute()]
    public partial class Jugador : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Cliente.ServiciosGestionUsuarios.Amigo[] AmigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Cliente.ServiciosGestionUsuarios.Amigo[] Amigo1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Cliente.ServiciosGestionUsuarios.Bloqueado[] BloqueadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Cliente.ServiciosGestionUsuarios.Bloqueado[] Bloqueado1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Cliente.ServiciosGestionUsuarios.DatosJugadorPartida[] DatosJugadorPartidaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string claveUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string contraseniaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string correoElectronicoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> esInvitadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string estadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] fotoPerfilField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idJugadorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreUsuarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Cliente.ServiciosGestionUsuarios.Amigo[] Amigo {
            get {
                return this.AmigoField;
            }
            set {
                if ((object.ReferenceEquals(this.AmigoField, value) != true)) {
                    this.AmigoField = value;
                    this.RaisePropertyChanged("Amigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Cliente.ServiciosGestionUsuarios.Amigo[] Amigo1 {
            get {
                return this.Amigo1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Amigo1Field, value) != true)) {
                    this.Amigo1Field = value;
                    this.RaisePropertyChanged("Amigo1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Cliente.ServiciosGestionUsuarios.Bloqueado[] Bloqueado {
            get {
                return this.BloqueadoField;
            }
            set {
                if ((object.ReferenceEquals(this.BloqueadoField, value) != true)) {
                    this.BloqueadoField = value;
                    this.RaisePropertyChanged("Bloqueado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Cliente.ServiciosGestionUsuarios.Bloqueado[] Bloqueado1 {
            get {
                return this.Bloqueado1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Bloqueado1Field, value) != true)) {
                    this.Bloqueado1Field = value;
                    this.RaisePropertyChanged("Bloqueado1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Cliente.ServiciosGestionUsuarios.DatosJugadorPartida[] DatosJugadorPartida {
            get {
                return this.DatosJugadorPartidaField;
            }
            set {
                if ((object.ReferenceEquals(this.DatosJugadorPartidaField, value) != true)) {
                    this.DatosJugadorPartidaField = value;
                    this.RaisePropertyChanged("DatosJugadorPartida");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string claveUsuario {
            get {
                return this.claveUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.claveUsuarioField, value) != true)) {
                    this.claveUsuarioField = value;
                    this.RaisePropertyChanged("claveUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string contrasenia {
            get {
                return this.contraseniaField;
            }
            set {
                if ((object.ReferenceEquals(this.contraseniaField, value) != true)) {
                    this.contraseniaField = value;
                    this.RaisePropertyChanged("contrasenia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string correoElectronico {
            get {
                return this.correoElectronicoField;
            }
            set {
                if ((object.ReferenceEquals(this.correoElectronicoField, value) != true)) {
                    this.correoElectronicoField = value;
                    this.RaisePropertyChanged("correoElectronico");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.descripcionField, value) != true)) {
                    this.descripcionField = value;
                    this.RaisePropertyChanged("descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> esInvitado {
            get {
                return this.esInvitadoField;
            }
            set {
                if ((this.esInvitadoField.Equals(value) != true)) {
                    this.esInvitadoField = value;
                    this.RaisePropertyChanged("esInvitado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string estado {
            get {
                return this.estadoField;
            }
            set {
                if ((object.ReferenceEquals(this.estadoField, value) != true)) {
                    this.estadoField = value;
                    this.RaisePropertyChanged("estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] fotoPerfil {
            get {
                return this.fotoPerfilField;
            }
            set {
                if ((object.ReferenceEquals(this.fotoPerfilField, value) != true)) {
                    this.fotoPerfilField = value;
                    this.RaisePropertyChanged("fotoPerfil");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idJugador {
            get {
                return this.idJugadorField;
            }
            set {
                if ((this.idJugadorField.Equals(value) != true)) {
                    this.idJugadorField = value;
                    this.RaisePropertyChanged("idJugador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombreUsuario {
            get {
                return this.nombreUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreUsuarioField, value) != true)) {
                    this.nombreUsuarioField = value;
                    this.RaisePropertyChanged("nombreUsuario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Amigo", Namespace="http://schemas.datacontract.org/2004/07/AccesoDatos")]
    [System.SerializableAttribute()]
    public partial class Amigo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Cliente.ServiciosGestionUsuarios.Jugador JugadorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Cliente.ServiciosGestionUsuarios.Jugador Jugador1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string estadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idAmigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idJugadorEmisorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idJugadorReceptorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Cliente.ServiciosGestionUsuarios.Jugador Jugador {
            get {
                return this.JugadorField;
            }
            set {
                if ((object.ReferenceEquals(this.JugadorField, value) != true)) {
                    this.JugadorField = value;
                    this.RaisePropertyChanged("Jugador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Cliente.ServiciosGestionUsuarios.Jugador Jugador1 {
            get {
                return this.Jugador1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Jugador1Field, value) != true)) {
                    this.Jugador1Field = value;
                    this.RaisePropertyChanged("Jugador1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string estado {
            get {
                return this.estadoField;
            }
            set {
                if ((object.ReferenceEquals(this.estadoField, value) != true)) {
                    this.estadoField = value;
                    this.RaisePropertyChanged("estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idAmigo {
            get {
                return this.idAmigoField;
            }
            set {
                if ((this.idAmigoField.Equals(value) != true)) {
                    this.idAmigoField = value;
                    this.RaisePropertyChanged("idAmigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idJugadorEmisor {
            get {
                return this.idJugadorEmisorField;
            }
            set {
                if ((this.idJugadorEmisorField.Equals(value) != true)) {
                    this.idJugadorEmisorField = value;
                    this.RaisePropertyChanged("idJugadorEmisor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idJugadorReceptor {
            get {
                return this.idJugadorReceptorField;
            }
            set {
                if ((this.idJugadorReceptorField.Equals(value) != true)) {
                    this.idJugadorReceptorField = value;
                    this.RaisePropertyChanged("idJugadorReceptor");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Bloqueado", Namespace="http://schemas.datacontract.org/2004/07/AccesoDatos")]
    [System.SerializableAttribute()]
    public partial class Bloqueado : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Cliente.ServiciosGestionUsuarios.Jugador JugadorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Cliente.ServiciosGestionUsuarios.Jugador Jugador1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idBloqueadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idJugadorEmisorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idJugadorReceptorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Cliente.ServiciosGestionUsuarios.Jugador Jugador {
            get {
                return this.JugadorField;
            }
            set {
                if ((object.ReferenceEquals(this.JugadorField, value) != true)) {
                    this.JugadorField = value;
                    this.RaisePropertyChanged("Jugador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Cliente.ServiciosGestionUsuarios.Jugador Jugador1 {
            get {
                return this.Jugador1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Jugador1Field, value) != true)) {
                    this.Jugador1Field = value;
                    this.RaisePropertyChanged("Jugador1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idBloqueado {
            get {
                return this.idBloqueadoField;
            }
            set {
                if ((this.idBloqueadoField.Equals(value) != true)) {
                    this.idBloqueadoField = value;
                    this.RaisePropertyChanged("idBloqueado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idJugadorEmisor {
            get {
                return this.idJugadorEmisorField;
            }
            set {
                if ((this.idJugadorEmisorField.Equals(value) != true)) {
                    this.idJugadorEmisorField = value;
                    this.RaisePropertyChanged("idJugadorEmisor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idJugadorReceptor {
            get {
                return this.idJugadorReceptorField;
            }
            set {
                if ((this.idJugadorReceptorField.Equals(value) != true)) {
                    this.idJugadorReceptorField = value;
                    this.RaisePropertyChanged("idJugadorReceptor");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DatosJugadorPartida", Namespace="http://schemas.datacontract.org/2004/07/AccesoDatos")]
    [System.SerializableAttribute()]
    public partial class DatosJugadorPartida : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Cliente.ServiciosGestionUsuarios.Jugador JugadorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Cliente.ServiciosGestionUsuarios.Partida PartidaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string claveJugadorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codigoPartidaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> esAdminField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> expulsadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> idAspectoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idDatosJugadorPartidaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idJugadorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> idPartidaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> puntajeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Cliente.ServiciosGestionUsuarios.Jugador Jugador {
            get {
                return this.JugadorField;
            }
            set {
                if ((object.ReferenceEquals(this.JugadorField, value) != true)) {
                    this.JugadorField = value;
                    this.RaisePropertyChanged("Jugador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Cliente.ServiciosGestionUsuarios.Partida Partida {
            get {
                return this.PartidaField;
            }
            set {
                if ((object.ReferenceEquals(this.PartidaField, value) != true)) {
                    this.PartidaField = value;
                    this.RaisePropertyChanged("Partida");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string claveJugador {
            get {
                return this.claveJugadorField;
            }
            set {
                if ((object.ReferenceEquals(this.claveJugadorField, value) != true)) {
                    this.claveJugadorField = value;
                    this.RaisePropertyChanged("claveJugador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string codigoPartida {
            get {
                return this.codigoPartidaField;
            }
            set {
                if ((object.ReferenceEquals(this.codigoPartidaField, value) != true)) {
                    this.codigoPartidaField = value;
                    this.RaisePropertyChanged("codigoPartida");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> esAdmin {
            get {
                return this.esAdminField;
            }
            set {
                if ((this.esAdminField.Equals(value) != true)) {
                    this.esAdminField = value;
                    this.RaisePropertyChanged("esAdmin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> expulsado {
            get {
                return this.expulsadoField;
            }
            set {
                if ((this.expulsadoField.Equals(value) != true)) {
                    this.expulsadoField = value;
                    this.RaisePropertyChanged("expulsado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> idAspecto {
            get {
                return this.idAspectoField;
            }
            set {
                if ((this.idAspectoField.Equals(value) != true)) {
                    this.idAspectoField = value;
                    this.RaisePropertyChanged("idAspecto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idDatosJugadorPartida {
            get {
                return this.idDatosJugadorPartidaField;
            }
            set {
                if ((this.idDatosJugadorPartidaField.Equals(value) != true)) {
                    this.idDatosJugadorPartidaField = value;
                    this.RaisePropertyChanged("idDatosJugadorPartida");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idJugador {
            get {
                return this.idJugadorField;
            }
            set {
                if ((this.idJugadorField.Equals(value) != true)) {
                    this.idJugadorField = value;
                    this.RaisePropertyChanged("idJugador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> idPartida {
            get {
                return this.idPartidaField;
            }
            set {
                if ((this.idPartidaField.Equals(value) != true)) {
                    this.idPartidaField = value;
                    this.RaisePropertyChanged("idPartida");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> puntaje {
            get {
                return this.puntajeField;
            }
            set {
                if ((this.puntajeField.Equals(value) != true)) {
                    this.puntajeField = value;
                    this.RaisePropertyChanged("puntaje");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Partida", Namespace="http://schemas.datacontract.org/2004/07/AccesoDatos")]
    [System.SerializableAttribute()]
    public partial class Partida : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Cliente.ServiciosGestionUsuarios.DatosJugadorPartida[] DatosJugadorPartidaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codigoPartidaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> duracionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string estadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> fechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idPartidaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreGanadorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> puntajeVictoriaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> tiempoGuerraField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Cliente.ServiciosGestionUsuarios.DatosJugadorPartida[] DatosJugadorPartida {
            get {
                return this.DatosJugadorPartidaField;
            }
            set {
                if ((object.ReferenceEquals(this.DatosJugadorPartidaField, value) != true)) {
                    this.DatosJugadorPartidaField = value;
                    this.RaisePropertyChanged("DatosJugadorPartida");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string codigoPartida {
            get {
                return this.codigoPartidaField;
            }
            set {
                if ((object.ReferenceEquals(this.codigoPartidaField, value) != true)) {
                    this.codigoPartidaField = value;
                    this.RaisePropertyChanged("codigoPartida");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> duracion {
            get {
                return this.duracionField;
            }
            set {
                if ((this.duracionField.Equals(value) != true)) {
                    this.duracionField = value;
                    this.RaisePropertyChanged("duracion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string estado {
            get {
                return this.estadoField;
            }
            set {
                if ((object.ReferenceEquals(this.estadoField, value) != true)) {
                    this.estadoField = value;
                    this.RaisePropertyChanged("estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> fecha {
            get {
                return this.fechaField;
            }
            set {
                if ((this.fechaField.Equals(value) != true)) {
                    this.fechaField = value;
                    this.RaisePropertyChanged("fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idPartida {
            get {
                return this.idPartidaField;
            }
            set {
                if ((this.idPartidaField.Equals(value) != true)) {
                    this.idPartidaField = value;
                    this.RaisePropertyChanged("idPartida");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombreGanador {
            get {
                return this.nombreGanadorField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreGanadorField, value) != true)) {
                    this.nombreGanadorField = value;
                    this.RaisePropertyChanged("nombreGanador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> puntajeVictoria {
            get {
                return this.puntajeVictoriaField;
            }
            set {
                if ((this.puntajeVictoriaField.Equals(value) != true)) {
                    this.puntajeVictoriaField = value;
                    this.RaisePropertyChanged("puntajeVictoria");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> tiempoGuerra {
            get {
                return this.tiempoGuerraField;
            }
            set {
                if ((this.tiempoGuerraField.Equals(value) != true)) {
                    this.tiempoGuerraField = value;
                    this.RaisePropertyChanged("tiempoGuerra");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Perfil", Namespace="http://schemas.datacontract.org/2004/07/Servicios.Interfaces")]
    [System.SerializableAttribute()]
    public partial class Perfil : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] FotoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreUsuarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Foto {
            get {
                return this.FotoField;
            }
            set {
                if ((object.ReferenceEquals(this.FotoField, value) != true)) {
                    this.FotoField = value;
                    this.RaisePropertyChanged("Foto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreUsuario {
            get {
                return this.NombreUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreUsuarioField, value) != true)) {
                    this.NombreUsuarioField = value;
                    this.RaisePropertyChanged("NombreUsuario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiciosGestionUsuarios.IServicioRegistrarUsuario")]
    public interface IServicioRegistrarUsuario {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioRegistrarUsuario/EnviarCodigoCorreo", ReplyAction="http://tempuri.org/IServicioRegistrarUsuario/EnviarCodigoCorreoResponse")]
        string EnviarCodigoCorreo(string correo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioRegistrarUsuario/EnviarCodigoCorreo", ReplyAction="http://tempuri.org/IServicioRegistrarUsuario/EnviarCodigoCorreoResponse")]
        System.Threading.Tasks.Task<string> EnviarCodigoCorreoAsync(string correo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioRegistrarUsuario/RegistrarUsuario", ReplyAction="http://tempuri.org/IServicioRegistrarUsuario/RegistrarUsuarioResponse")]
        bool RegistrarUsuario(Cliente.ServiciosGestionUsuarios.Usuario usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioRegistrarUsuario/RegistrarUsuario", ReplyAction="http://tempuri.org/IServicioRegistrarUsuario/RegistrarUsuarioResponse")]
        System.Threading.Tasks.Task<bool> RegistrarUsuarioAsync(Cliente.ServiciosGestionUsuarios.Usuario usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioRegistrarUsuario/ValidarNombreNoRepetido", ReplyAction="http://tempuri.org/IServicioRegistrarUsuario/ValidarNombreNoRepetidoResponse")]
        bool ValidarNombreNoRepetido(string nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioRegistrarUsuario/ValidarNombreNoRepetido", ReplyAction="http://tempuri.org/IServicioRegistrarUsuario/ValidarNombreNoRepetidoResponse")]
        System.Threading.Tasks.Task<bool> ValidarNombreNoRepetidoAsync(string nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioRegistrarUsuario/ValidarCorreoNoRepetido", ReplyAction="http://tempuri.org/IServicioRegistrarUsuario/ValidarCorreoNoRepetidoResponse")]
        bool ValidarCorreoNoRepetido(string correo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioRegistrarUsuario/ValidarCorreoNoRepetido", ReplyAction="http://tempuri.org/IServicioRegistrarUsuario/ValidarCorreoNoRepetidoResponse")]
        System.Threading.Tasks.Task<bool> ValidarCorreoNoRepetidoAsync(string correo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioRegistrarUsuarioChannel : Cliente.ServiciosGestionUsuarios.IServicioRegistrarUsuario, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioRegistrarUsuarioClient : System.ServiceModel.ClientBase<Cliente.ServiciosGestionUsuarios.IServicioRegistrarUsuario>, Cliente.ServiciosGestionUsuarios.IServicioRegistrarUsuario {
        
        public ServicioRegistrarUsuarioClient() {
        }
        
        public ServicioRegistrarUsuarioClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioRegistrarUsuarioClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioRegistrarUsuarioClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioRegistrarUsuarioClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string EnviarCodigoCorreo(string correo) {
            return base.Channel.EnviarCodigoCorreo(correo);
        }
        
        public System.Threading.Tasks.Task<string> EnviarCodigoCorreoAsync(string correo) {
            return base.Channel.EnviarCodigoCorreoAsync(correo);
        }
        
        public bool RegistrarUsuario(Cliente.ServiciosGestionUsuarios.Usuario usuario) {
            return base.Channel.RegistrarUsuario(usuario);
        }
        
        public System.Threading.Tasks.Task<bool> RegistrarUsuarioAsync(Cliente.ServiciosGestionUsuarios.Usuario usuario) {
            return base.Channel.RegistrarUsuarioAsync(usuario);
        }
        
        public bool ValidarNombreNoRepetido(string nombre) {
            return base.Channel.ValidarNombreNoRepetido(nombre);
        }
        
        public System.Threading.Tasks.Task<bool> ValidarNombreNoRepetidoAsync(string nombre) {
            return base.Channel.ValidarNombreNoRepetidoAsync(nombre);
        }
        
        public bool ValidarCorreoNoRepetido(string correo) {
            return base.Channel.ValidarCorreoNoRepetido(correo);
        }
        
        public System.Threading.Tasks.Task<bool> ValidarCorreoNoRepetidoAsync(string correo) {
            return base.Channel.ValidarCorreoNoRepetidoAsync(correo);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiciosGestionUsuarios.IServicioLogin")]
    public interface IServicioLogin {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioLogin/Login", ReplyAction="http://tempuri.org/IServicioLogin/LoginResponse")]
        Cliente.ServiciosGestionUsuarios.Jugador Login(string nombreUsuario, string contrasenia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioLogin/Login", ReplyAction="http://tempuri.org/IServicioLogin/LoginResponse")]
        System.Threading.Tasks.Task<Cliente.ServiciosGestionUsuarios.Jugador> LoginAsync(string nombreUsuario, string contrasenia);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioLoginChannel : Cliente.ServiciosGestionUsuarios.IServicioLogin, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioLoginClient : System.ServiceModel.ClientBase<Cliente.ServiciosGestionUsuarios.IServicioLogin>, Cliente.ServiciosGestionUsuarios.IServicioLogin {
        
        public ServicioLoginClient() {
        }
        
        public ServicioLoginClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioLoginClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioLoginClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioLoginClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Cliente.ServiciosGestionUsuarios.Jugador Login(string nombreUsuario, string contrasenia) {
            return base.Channel.Login(nombreUsuario, contrasenia);
        }
        
        public System.Threading.Tasks.Task<Cliente.ServiciosGestionUsuarios.Jugador> LoginAsync(string nombreUsuario, string contrasenia) {
            return base.Channel.LoginAsync(nombreUsuario, contrasenia);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiciosGestionUsuarios.IServicioPersonalizarPerfil")]
    public interface IServicioPersonalizarPerfil {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPersonalizarPerfil/GuardarCambios", ReplyAction="http://tempuri.org/IServicioPersonalizarPerfil/GuardarCambiosResponse")]
        bool GuardarCambios(Cliente.ServiciosGestionUsuarios.Perfil perfil, string claveUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPersonalizarPerfil/GuardarCambios", ReplyAction="http://tempuri.org/IServicioPersonalizarPerfil/GuardarCambiosResponse")]
        System.Threading.Tasks.Task<bool> GuardarCambiosAsync(Cliente.ServiciosGestionUsuarios.Perfil perfil, string claveUsuario);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioPersonalizarPerfilChannel : Cliente.ServiciosGestionUsuarios.IServicioPersonalizarPerfil, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioPersonalizarPerfilClient : System.ServiceModel.ClientBase<Cliente.ServiciosGestionUsuarios.IServicioPersonalizarPerfil>, Cliente.ServiciosGestionUsuarios.IServicioPersonalizarPerfil {
        
        public ServicioPersonalizarPerfilClient() {
        }
        
        public ServicioPersonalizarPerfilClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioPersonalizarPerfilClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioPersonalizarPerfilClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioPersonalizarPerfilClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool GuardarCambios(Cliente.ServiciosGestionUsuarios.Perfil perfil, string claveUsuario) {
            return base.Channel.GuardarCambios(perfil, claveUsuario);
        }
        
        public System.Threading.Tasks.Task<bool> GuardarCambiosAsync(Cliente.ServiciosGestionUsuarios.Perfil perfil, string claveUsuario) {
            return base.Channel.GuardarCambiosAsync(perfil, claveUsuario);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiciosGestionUsuarios.IServicioCambiarContrasenia")]
    public interface IServicioCambiarContrasenia {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCambiarContrasenia/CambiarContrasenia", ReplyAction="http://tempuri.org/IServicioCambiarContrasenia/CambiarContraseniaResponse")]
        bool CambiarContrasenia(string contrasenia, string correo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCambiarContrasenia/CambiarContrasenia", ReplyAction="http://tempuri.org/IServicioCambiarContrasenia/CambiarContraseniaResponse")]
        System.Threading.Tasks.Task<bool> CambiarContraseniaAsync(string contrasenia, string correo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCambiarContrasenia/EnviarCorreoRecuperacion", ReplyAction="http://tempuri.org/IServicioCambiarContrasenia/EnviarCorreoRecuperacionResponse")]
        string EnviarCorreoRecuperacion(string correo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCambiarContrasenia/EnviarCorreoRecuperacion", ReplyAction="http://tempuri.org/IServicioCambiarContrasenia/EnviarCorreoRecuperacionResponse")]
        System.Threading.Tasks.Task<string> EnviarCorreoRecuperacionAsync(string correo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCambiarContrasenia/VerificarExistenciaUsuario", ReplyAction="http://tempuri.org/IServicioCambiarContrasenia/VerificarExistenciaUsuarioResponse" +
            "")]
        string VerificarExistenciaUsuario(string nombreOCorreo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCambiarContrasenia/VerificarExistenciaUsuario", ReplyAction="http://tempuri.org/IServicioCambiarContrasenia/VerificarExistenciaUsuarioResponse" +
            "")]
        System.Threading.Tasks.Task<string> VerificarExistenciaUsuarioAsync(string nombreOCorreo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioCambiarContraseniaChannel : Cliente.ServiciosGestionUsuarios.IServicioCambiarContrasenia, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioCambiarContraseniaClient : System.ServiceModel.ClientBase<Cliente.ServiciosGestionUsuarios.IServicioCambiarContrasenia>, Cliente.ServiciosGestionUsuarios.IServicioCambiarContrasenia {
        
        public ServicioCambiarContraseniaClient() {
        }
        
        public ServicioCambiarContraseniaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioCambiarContraseniaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioCambiarContraseniaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioCambiarContraseniaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool CambiarContrasenia(string contrasenia, string correo) {
            return base.Channel.CambiarContrasenia(contrasenia, correo);
        }
        
        public System.Threading.Tasks.Task<bool> CambiarContraseniaAsync(string contrasenia, string correo) {
            return base.Channel.CambiarContraseniaAsync(contrasenia, correo);
        }
        
        public string EnviarCorreoRecuperacion(string correo) {
            return base.Channel.EnviarCorreoRecuperacion(correo);
        }
        
        public System.Threading.Tasks.Task<string> EnviarCorreoRecuperacionAsync(string correo) {
            return base.Channel.EnviarCorreoRecuperacionAsync(correo);
        }
        
        public string VerificarExistenciaUsuario(string nombreOCorreo) {
            return base.Channel.VerificarExistenciaUsuario(nombreOCorreo);
        }
        
        public System.Threading.Tasks.Task<string> VerificarExistenciaUsuarioAsync(string nombreOCorreo) {
            return base.Channel.VerificarExistenciaUsuarioAsync(nombreOCorreo);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiciosGestionUsuarios.IServicioSolicitudes", CallbackContract=typeof(Cliente.ServiciosGestionUsuarios.IServicioSolicitudesCallback))]
    public interface IServicioSolicitudes {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioSolicitudes/EnviarSolicitud", ReplyAction="http://tempuri.org/IServicioSolicitudes/EnviarSolicitudResponse")]
        int EnviarSolicitud(string claveJugadorRemitente, int idJugador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioSolicitudes/EnviarSolicitud", ReplyAction="http://tempuri.org/IServicioSolicitudes/EnviarSolicitudResponse")]
        System.Threading.Tasks.Task<int> EnviarSolicitudAsync(string claveJugadorRemitente, int idJugador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioSolicitudes/RecibirSolicitudes", ReplyAction="http://tempuri.org/IServicioSolicitudes/RecibirSolicitudesResponse")]
        Cliente.ServiciosGestionUsuarios.Jugador[] RecibirSolicitudes(int idJugador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioSolicitudes/RecibirSolicitudes", ReplyAction="http://tempuri.org/IServicioSolicitudes/RecibirSolicitudesResponse")]
        System.Threading.Tasks.Task<Cliente.ServiciosGestionUsuarios.Jugador[]> RecibirSolicitudesAsync(int idJugador);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServicioSolicitudes/AceptarSolicitud")]
        void AceptarSolicitud(int idJugadorEmisor, int idJugadorReceptor);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServicioSolicitudes/AceptarSolicitud")]
        System.Threading.Tasks.Task AceptarSolicitudAsync(int idJugadorEmisor, int idJugadorReceptor);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServicioSolicitudes/RechazarSolicitud")]
        void RechazarSolicitud(int idJugadorEmisor, int idJugadorReceptor);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServicioSolicitudes/RechazarSolicitud")]
        System.Threading.Tasks.Task RechazarSolicitudAsync(int idJugadorEmisor, int idJugadorReceptor);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServicioSolicitudes/EnviarInvitacion")]
        void EnviarInvitacion(string codigoPartida, string correoJugadorInvitado, string nombreUsuarioInvitador);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServicioSolicitudes/EnviarInvitacion")]
        System.Threading.Tasks.Task EnviarInvitacionAsync(string codigoPartida, string correoJugadorInvitado, string nombreUsuarioInvitador);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServicioSolicitudes/EnviarCliente")]
        void EnviarCliente(int idJugador);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServicioSolicitudes/EnviarCliente")]
        System.Threading.Tasks.Task EnviarClienteAsync(int idJugador);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioSolicitudesCallback {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioSolicitudes/ObtenerNuevaSolicitud", ReplyAction="http://tempuri.org/IServicioSolicitudes/ObtenerNuevaSolicitudResponse")]
        void ObtenerNuevaSolicitud(Cliente.ServiciosGestionUsuarios.Jugador solicitud);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioSolicitudes/ObtenerAmigoNuevo", ReplyAction="http://tempuri.org/IServicioSolicitudes/ObtenerAmigoNuevoResponse")]
        void ObtenerAmigoNuevo(Cliente.ServiciosGestionUsuarios.Jugador amigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioSolicitudes/EnviarEliminacionAmigo", ReplyAction="http://tempuri.org/IServicioSolicitudes/EnviarEliminacionAmigoResponse")]
        void EnviarEliminacionAmigo(int idJugadorEmisor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioSolicitudes/ObtenerNuevoBloqueo", ReplyAction="http://tempuri.org/IServicioSolicitudes/ObtenerNuevoBloqueoResponse")]
        void ObtenerNuevoBloqueo(Cliente.ServiciosGestionUsuarios.Jugador bloqueado);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioSolicitudesChannel : Cliente.ServiciosGestionUsuarios.IServicioSolicitudes, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioSolicitudesClient : System.ServiceModel.DuplexClientBase<Cliente.ServiciosGestionUsuarios.IServicioSolicitudes>, Cliente.ServiciosGestionUsuarios.IServicioSolicitudes {
        
        public ServicioSolicitudesClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public ServicioSolicitudesClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public ServicioSolicitudesClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioSolicitudesClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioSolicitudesClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public int EnviarSolicitud(string claveJugadorRemitente, int idJugador) {
            return base.Channel.EnviarSolicitud(claveJugadorRemitente, idJugador);
        }
        
        public System.Threading.Tasks.Task<int> EnviarSolicitudAsync(string claveJugadorRemitente, int idJugador) {
            return base.Channel.EnviarSolicitudAsync(claveJugadorRemitente, idJugador);
        }
        
        public Cliente.ServiciosGestionUsuarios.Jugador[] RecibirSolicitudes(int idJugador) {
            return base.Channel.RecibirSolicitudes(idJugador);
        }
        
        public System.Threading.Tasks.Task<Cliente.ServiciosGestionUsuarios.Jugador[]> RecibirSolicitudesAsync(int idJugador) {
            return base.Channel.RecibirSolicitudesAsync(idJugador);
        }
        
        public void AceptarSolicitud(int idJugadorEmisor, int idJugadorReceptor) {
            base.Channel.AceptarSolicitud(idJugadorEmisor, idJugadorReceptor);
        }
        
        public System.Threading.Tasks.Task AceptarSolicitudAsync(int idJugadorEmisor, int idJugadorReceptor) {
            return base.Channel.AceptarSolicitudAsync(idJugadorEmisor, idJugadorReceptor);
        }
        
        public void RechazarSolicitud(int idJugadorEmisor, int idJugadorReceptor) {
            base.Channel.RechazarSolicitud(idJugadorEmisor, idJugadorReceptor);
        }
        
        public System.Threading.Tasks.Task RechazarSolicitudAsync(int idJugadorEmisor, int idJugadorReceptor) {
            return base.Channel.RechazarSolicitudAsync(idJugadorEmisor, idJugadorReceptor);
        }
        
        public void EnviarInvitacion(string codigoPartida, string correoJugadorInvitado, string nombreUsuarioInvitador) {
            base.Channel.EnviarInvitacion(codigoPartida, correoJugadorInvitado, nombreUsuarioInvitador);
        }
        
        public System.Threading.Tasks.Task EnviarInvitacionAsync(string codigoPartida, string correoJugadorInvitado, string nombreUsuarioInvitador) {
            return base.Channel.EnviarInvitacionAsync(codigoPartida, correoJugadorInvitado, nombreUsuarioInvitador);
        }
        
        public void EnviarCliente(int idJugador) {
            base.Channel.EnviarCliente(idJugador);
        }
        
        public System.Threading.Tasks.Task EnviarClienteAsync(int idJugador) {
            return base.Channel.EnviarClienteAsync(idJugador);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiciosGestionUsuarios.IServicioAmigos")]
    public interface IServicioAmigos {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAmigos/CargarAmigos", ReplyAction="http://tempuri.org/IServicioAmigos/CargarAmigosResponse")]
        Cliente.ServiciosGestionUsuarios.Jugador[] CargarAmigos(int idJugador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAmigos/CargarAmigos", ReplyAction="http://tempuri.org/IServicioAmigos/CargarAmigosResponse")]
        System.Threading.Tasks.Task<Cliente.ServiciosGestionUsuarios.Jugador[]> CargarAmigosAsync(int idJugador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAmigos/EliminarAmigo", ReplyAction="http://tempuri.org/IServicioAmigos/EliminarAmigoResponse")]
        void EliminarAmigo(int idJugadorEmisor, int idJugadorReceptor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAmigos/EliminarAmigo", ReplyAction="http://tempuri.org/IServicioAmigos/EliminarAmigoResponse")]
        System.Threading.Tasks.Task EliminarAmigoAsync(int idJugadorEmisor, int idJugadorReceptor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAmigos/BloquearJugador", ReplyAction="http://tempuri.org/IServicioAmigos/BloquearJugadorResponse")]
        int BloquearJugador(int idJugadorEmisor, string claveJugadorReceptor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAmigos/BloquearJugador", ReplyAction="http://tempuri.org/IServicioAmigos/BloquearJugadorResponse")]
        System.Threading.Tasks.Task<int> BloquearJugadorAsync(int idJugadorEmisor, string claveJugadorReceptor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAmigos/DesbloquearJugador", ReplyAction="http://tempuri.org/IServicioAmigos/DesbloquearJugadorResponse")]
        void DesbloquearJugador(int idJugadorEmisor, int idJugadorRemitente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAmigos/DesbloquearJugador", ReplyAction="http://tempuri.org/IServicioAmigos/DesbloquearJugadorResponse")]
        System.Threading.Tasks.Task DesbloquearJugadorAsync(int idJugadorEmisor, int idJugadorRemitente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAmigos/CargarBloqueados", ReplyAction="http://tempuri.org/IServicioAmigos/CargarBloqueadosResponse")]
        Cliente.ServiciosGestionUsuarios.Jugador[] CargarBloqueados(int idJugadorEmisor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAmigos/CargarBloqueados", ReplyAction="http://tempuri.org/IServicioAmigos/CargarBloqueadosResponse")]
        System.Threading.Tasks.Task<Cliente.ServiciosGestionUsuarios.Jugador[]> CargarBloqueadosAsync(int idJugadorEmisor);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioAmigosChannel : Cliente.ServiciosGestionUsuarios.IServicioAmigos, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioAmigosClient : System.ServiceModel.ClientBase<Cliente.ServiciosGestionUsuarios.IServicioAmigos>, Cliente.ServiciosGestionUsuarios.IServicioAmigos {
        
        public ServicioAmigosClient() {
        }
        
        public ServicioAmigosClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioAmigosClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioAmigosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioAmigosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Cliente.ServiciosGestionUsuarios.Jugador[] CargarAmigos(int idJugador) {
            return base.Channel.CargarAmigos(idJugador);
        }
        
        public System.Threading.Tasks.Task<Cliente.ServiciosGestionUsuarios.Jugador[]> CargarAmigosAsync(int idJugador) {
            return base.Channel.CargarAmigosAsync(idJugador);
        }
        
        public void EliminarAmigo(int idJugadorEmisor, int idJugadorReceptor) {
            base.Channel.EliminarAmigo(idJugadorEmisor, idJugadorReceptor);
        }
        
        public System.Threading.Tasks.Task EliminarAmigoAsync(int idJugadorEmisor, int idJugadorReceptor) {
            return base.Channel.EliminarAmigoAsync(idJugadorEmisor, idJugadorReceptor);
        }
        
        public int BloquearJugador(int idJugadorEmisor, string claveJugadorReceptor) {
            return base.Channel.BloquearJugador(idJugadorEmisor, claveJugadorReceptor);
        }
        
        public System.Threading.Tasks.Task<int> BloquearJugadorAsync(int idJugadorEmisor, string claveJugadorReceptor) {
            return base.Channel.BloquearJugadorAsync(idJugadorEmisor, claveJugadorReceptor);
        }
        
        public void DesbloquearJugador(int idJugadorEmisor, int idJugadorRemitente) {
            base.Channel.DesbloquearJugador(idJugadorEmisor, idJugadorRemitente);
        }
        
        public System.Threading.Tasks.Task DesbloquearJugadorAsync(int idJugadorEmisor, int idJugadorRemitente) {
            return base.Channel.DesbloquearJugadorAsync(idJugadorEmisor, idJugadorRemitente);
        }
        
        public Cliente.ServiciosGestionUsuarios.Jugador[] CargarBloqueados(int idJugadorEmisor) {
            return base.Channel.CargarBloqueados(idJugadorEmisor);
        }
        
        public System.Threading.Tasks.Task<Cliente.ServiciosGestionUsuarios.Jugador[]> CargarBloqueadosAsync(int idJugadorEmisor) {
            return base.Channel.CargarBloqueadosAsync(idJugadorEmisor);
        }
    }
}
