//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cliente.ServiciosGestionUsuarios {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Usuario", Namespace="http://schemas.datacontract.org/2004/07/Servicios.Interfaces")]
    [System.SerializableAttribute()]
    public partial class Usuario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContraseniaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CorreoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreUsuarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Contrasenia {
            get {
                return this.ContraseniaField;
            }
            set {
                if ((object.ReferenceEquals(this.ContraseniaField, value) != true)) {
                    this.ContraseniaField = value;
                    this.RaisePropertyChanged("Contrasenia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Correo {
            get {
                return this.CorreoField;
            }
            set {
                if ((object.ReferenceEquals(this.CorreoField, value) != true)) {
                    this.CorreoField = value;
                    this.RaisePropertyChanged("Correo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreUsuario {
            get {
                return this.NombreUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreUsuarioField, value) != true)) {
                    this.NombreUsuarioField = value;
                    this.RaisePropertyChanged("NombreUsuario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Jugador", Namespace="http://schemas.datacontract.org/2004/07/AccesoDatos")]
    [System.SerializableAttribute()]
    public partial class Jugador : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Cliente.ServiciosGestionUsuarios.DatosJugadorPartida[] DatosJugadorPartidaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Cliente.ServiciosGestionUsuarios.SolicitudAmigo[] SolicitudAmigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Cliente.ServiciosGestionUsuarios.SolicitudBloqueo[] SolicitudBloqueoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string claveUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string contraseniaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string correoElectronicoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> esInvitadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string estadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] fotoPerfilField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idJugadorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreUsuarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Cliente.ServiciosGestionUsuarios.DatosJugadorPartida[] DatosJugadorPartida {
            get {
                return this.DatosJugadorPartidaField;
            }
            set {
                if ((object.ReferenceEquals(this.DatosJugadorPartidaField, value) != true)) {
                    this.DatosJugadorPartidaField = value;
                    this.RaisePropertyChanged("DatosJugadorPartida");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Cliente.ServiciosGestionUsuarios.SolicitudAmigo[] SolicitudAmigo {
            get {
                return this.SolicitudAmigoField;
            }
            set {
                if ((object.ReferenceEquals(this.SolicitudAmigoField, value) != true)) {
                    this.SolicitudAmigoField = value;
                    this.RaisePropertyChanged("SolicitudAmigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Cliente.ServiciosGestionUsuarios.SolicitudBloqueo[] SolicitudBloqueo {
            get {
                return this.SolicitudBloqueoField;
            }
            set {
                if ((object.ReferenceEquals(this.SolicitudBloqueoField, value) != true)) {
                    this.SolicitudBloqueoField = value;
                    this.RaisePropertyChanged("SolicitudBloqueo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string claveUsuario {
            get {
                return this.claveUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.claveUsuarioField, value) != true)) {
                    this.claveUsuarioField = value;
                    this.RaisePropertyChanged("claveUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string contrasenia {
            get {
                return this.contraseniaField;
            }
            set {
                if ((object.ReferenceEquals(this.contraseniaField, value) != true)) {
                    this.contraseniaField = value;
                    this.RaisePropertyChanged("contrasenia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string correoElectronico {
            get {
                return this.correoElectronicoField;
            }
            set {
                if ((object.ReferenceEquals(this.correoElectronicoField, value) != true)) {
                    this.correoElectronicoField = value;
                    this.RaisePropertyChanged("correoElectronico");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.descripcionField, value) != true)) {
                    this.descripcionField = value;
                    this.RaisePropertyChanged("descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> esInvitado {
            get {
                return this.esInvitadoField;
            }
            set {
                if ((this.esInvitadoField.Equals(value) != true)) {
                    this.esInvitadoField = value;
                    this.RaisePropertyChanged("esInvitado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string estado {
            get {
                return this.estadoField;
            }
            set {
                if ((object.ReferenceEquals(this.estadoField, value) != true)) {
                    this.estadoField = value;
                    this.RaisePropertyChanged("estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] fotoPerfil {
            get {
                return this.fotoPerfilField;
            }
            set {
                if ((object.ReferenceEquals(this.fotoPerfilField, value) != true)) {
                    this.fotoPerfilField = value;
                    this.RaisePropertyChanged("fotoPerfil");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idJugador {
            get {
                return this.idJugadorField;
            }
            set {
                if ((this.idJugadorField.Equals(value) != true)) {
                    this.idJugadorField = value;
                    this.RaisePropertyChanged("idJugador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombreUsuario {
            get {
                return this.nombreUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreUsuarioField, value) != true)) {
                    this.nombreUsuarioField = value;
                    this.RaisePropertyChanged("nombreUsuario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DatosJugadorPartida", Namespace="http://schemas.datacontract.org/2004/07/AccesoDatos")]
    [System.SerializableAttribute()]
    public partial class DatosJugadorPartida : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Cliente.ServiciosGestionUsuarios.Jugador JugadorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Cliente.ServiciosGestionUsuarios.Partida PartidaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string claveJugadorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codigoPartidaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> esAdminField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> expulsadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> idAspectoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idDatosJugadorPartidaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idJugadorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> idPartidaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> puntajeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Cliente.ServiciosGestionUsuarios.Jugador Jugador {
            get {
                return this.JugadorField;
            }
            set {
                if ((object.ReferenceEquals(this.JugadorField, value) != true)) {
                    this.JugadorField = value;
                    this.RaisePropertyChanged("Jugador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Cliente.ServiciosGestionUsuarios.Partida Partida {
            get {
                return this.PartidaField;
            }
            set {
                if ((object.ReferenceEquals(this.PartidaField, value) != true)) {
                    this.PartidaField = value;
                    this.RaisePropertyChanged("Partida");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string claveJugador {
            get {
                return this.claveJugadorField;
            }
            set {
                if ((object.ReferenceEquals(this.claveJugadorField, value) != true)) {
                    this.claveJugadorField = value;
                    this.RaisePropertyChanged("claveJugador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string codigoPartida {
            get {
                return this.codigoPartidaField;
            }
            set {
                if ((object.ReferenceEquals(this.codigoPartidaField, value) != true)) {
                    this.codigoPartidaField = value;
                    this.RaisePropertyChanged("codigoPartida");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> esAdmin {
            get {
                return this.esAdminField;
            }
            set {
                if ((this.esAdminField.Equals(value) != true)) {
                    this.esAdminField = value;
                    this.RaisePropertyChanged("esAdmin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> expulsado {
            get {
                return this.expulsadoField;
            }
            set {
                if ((this.expulsadoField.Equals(value) != true)) {
                    this.expulsadoField = value;
                    this.RaisePropertyChanged("expulsado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> idAspecto {
            get {
                return this.idAspectoField;
            }
            set {
                if ((this.idAspectoField.Equals(value) != true)) {
                    this.idAspectoField = value;
                    this.RaisePropertyChanged("idAspecto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idDatosJugadorPartida {
            get {
                return this.idDatosJugadorPartidaField;
            }
            set {
                if ((this.idDatosJugadorPartidaField.Equals(value) != true)) {
                    this.idDatosJugadorPartidaField = value;
                    this.RaisePropertyChanged("idDatosJugadorPartida");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idJugador {
            get {
                return this.idJugadorField;
            }
            set {
                if ((this.idJugadorField.Equals(value) != true)) {
                    this.idJugadorField = value;
                    this.RaisePropertyChanged("idJugador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> idPartida {
            get {
                return this.idPartidaField;
            }
            set {
                if ((this.idPartidaField.Equals(value) != true)) {
                    this.idPartidaField = value;
                    this.RaisePropertyChanged("idPartida");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> puntaje {
            get {
                return this.puntajeField;
            }
            set {
                if ((this.puntajeField.Equals(value) != true)) {
                    this.puntajeField = value;
                    this.RaisePropertyChanged("puntaje");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SolicitudAmigo", Namespace="http://schemas.datacontract.org/2004/07/AccesoDatos")]
    [System.SerializableAttribute()]
    public partial class SolicitudAmigo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Cliente.ServiciosGestionUsuarios.Amigo AmigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Cliente.ServiciosGestionUsuarios.Jugador JugadorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string estadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> fechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idAmigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idJugadorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idSolicitudAmigoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Cliente.ServiciosGestionUsuarios.Amigo Amigo {
            get {
                return this.AmigoField;
            }
            set {
                if ((object.ReferenceEquals(this.AmigoField, value) != true)) {
                    this.AmigoField = value;
                    this.RaisePropertyChanged("Amigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Cliente.ServiciosGestionUsuarios.Jugador Jugador {
            get {
                return this.JugadorField;
            }
            set {
                if ((object.ReferenceEquals(this.JugadorField, value) != true)) {
                    this.JugadorField = value;
                    this.RaisePropertyChanged("Jugador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string estado {
            get {
                return this.estadoField;
            }
            set {
                if ((object.ReferenceEquals(this.estadoField, value) != true)) {
                    this.estadoField = value;
                    this.RaisePropertyChanged("estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> fecha {
            get {
                return this.fechaField;
            }
            set {
                if ((this.fechaField.Equals(value) != true)) {
                    this.fechaField = value;
                    this.RaisePropertyChanged("fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idAmigo {
            get {
                return this.idAmigoField;
            }
            set {
                if ((this.idAmigoField.Equals(value) != true)) {
                    this.idAmigoField = value;
                    this.RaisePropertyChanged("idAmigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idJugador {
            get {
                return this.idJugadorField;
            }
            set {
                if ((this.idJugadorField.Equals(value) != true)) {
                    this.idJugadorField = value;
                    this.RaisePropertyChanged("idJugador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idSolicitudAmigo {
            get {
                return this.idSolicitudAmigoField;
            }
            set {
                if ((this.idSolicitudAmigoField.Equals(value) != true)) {
                    this.idSolicitudAmigoField = value;
                    this.RaisePropertyChanged("idSolicitudAmigo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SolicitudBloqueo", Namespace="http://schemas.datacontract.org/2004/07/AccesoDatos")]
    [System.SerializableAttribute()]
    public partial class SolicitudBloqueo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Cliente.ServiciosGestionUsuarios.Bloqueado BloqueadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Cliente.ServiciosGestionUsuarios.Jugador JugadorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string claveJugadorBloqueadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string claveJugadorEmisorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> idBloqueadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> idJugadorEmisorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idSolicitudBloqueoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Cliente.ServiciosGestionUsuarios.Bloqueado Bloqueado {
            get {
                return this.BloqueadoField;
            }
            set {
                if ((object.ReferenceEquals(this.BloqueadoField, value) != true)) {
                    this.BloqueadoField = value;
                    this.RaisePropertyChanged("Bloqueado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Cliente.ServiciosGestionUsuarios.Jugador Jugador {
            get {
                return this.JugadorField;
            }
            set {
                if ((object.ReferenceEquals(this.JugadorField, value) != true)) {
                    this.JugadorField = value;
                    this.RaisePropertyChanged("Jugador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string claveJugadorBloqueado {
            get {
                return this.claveJugadorBloqueadoField;
            }
            set {
                if ((object.ReferenceEquals(this.claveJugadorBloqueadoField, value) != true)) {
                    this.claveJugadorBloqueadoField = value;
                    this.RaisePropertyChanged("claveJugadorBloqueado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string claveJugadorEmisor {
            get {
                return this.claveJugadorEmisorField;
            }
            set {
                if ((object.ReferenceEquals(this.claveJugadorEmisorField, value) != true)) {
                    this.claveJugadorEmisorField = value;
                    this.RaisePropertyChanged("claveJugadorEmisor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> idBloqueado {
            get {
                return this.idBloqueadoField;
            }
            set {
                if ((this.idBloqueadoField.Equals(value) != true)) {
                    this.idBloqueadoField = value;
                    this.RaisePropertyChanged("idBloqueado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> idJugadorEmisor {
            get {
                return this.idJugadorEmisorField;
            }
            set {
                if ((this.idJugadorEmisorField.Equals(value) != true)) {
                    this.idJugadorEmisorField = value;
                    this.RaisePropertyChanged("idJugadorEmisor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idSolicitudBloqueo {
            get {
                return this.idSolicitudBloqueoField;
            }
            set {
                if ((this.idSolicitudBloqueoField.Equals(value) != true)) {
                    this.idSolicitudBloqueoField = value;
                    this.RaisePropertyChanged("idSolicitudBloqueo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Partida", Namespace="http://schemas.datacontract.org/2004/07/AccesoDatos")]
    [System.SerializableAttribute()]
    public partial class Partida : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Cliente.ServiciosGestionUsuarios.DatosJugadorPartida[] DatosJugadorPartidaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codigoPartidaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> duracionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string estadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> fechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idPartidaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreGanadorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> puntajeVictoriaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> tiempoGuerraField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Cliente.ServiciosGestionUsuarios.DatosJugadorPartida[] DatosJugadorPartida {
            get {
                return this.DatosJugadorPartidaField;
            }
            set {
                if ((object.ReferenceEquals(this.DatosJugadorPartidaField, value) != true)) {
                    this.DatosJugadorPartidaField = value;
                    this.RaisePropertyChanged("DatosJugadorPartida");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string codigoPartida {
            get {
                return this.codigoPartidaField;
            }
            set {
                if ((object.ReferenceEquals(this.codigoPartidaField, value) != true)) {
                    this.codigoPartidaField = value;
                    this.RaisePropertyChanged("codigoPartida");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> duracion {
            get {
                return this.duracionField;
            }
            set {
                if ((this.duracionField.Equals(value) != true)) {
                    this.duracionField = value;
                    this.RaisePropertyChanged("duracion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string estado {
            get {
                return this.estadoField;
            }
            set {
                if ((object.ReferenceEquals(this.estadoField, value) != true)) {
                    this.estadoField = value;
                    this.RaisePropertyChanged("estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> fecha {
            get {
                return this.fechaField;
            }
            set {
                if ((this.fechaField.Equals(value) != true)) {
                    this.fechaField = value;
                    this.RaisePropertyChanged("fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idPartida {
            get {
                return this.idPartidaField;
            }
            set {
                if ((this.idPartidaField.Equals(value) != true)) {
                    this.idPartidaField = value;
                    this.RaisePropertyChanged("idPartida");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombreGanador {
            get {
                return this.nombreGanadorField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreGanadorField, value) != true)) {
                    this.nombreGanadorField = value;
                    this.RaisePropertyChanged("nombreGanador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> puntajeVictoria {
            get {
                return this.puntajeVictoriaField;
            }
            set {
                if ((this.puntajeVictoriaField.Equals(value) != true)) {
                    this.puntajeVictoriaField = value;
                    this.RaisePropertyChanged("puntajeVictoria");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> tiempoGuerra {
            get {
                return this.tiempoGuerraField;
            }
            set {
                if ((this.tiempoGuerraField.Equals(value) != true)) {
                    this.tiempoGuerraField = value;
                    this.RaisePropertyChanged("tiempoGuerra");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Amigo", Namespace="http://schemas.datacontract.org/2004/07/AccesoDatos")]
    [System.SerializableAttribute()]
    public partial class Amigo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Cliente.ServiciosGestionUsuarios.SolicitudAmigo[] SolicitudAmigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string claveUsuarioAmigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idAmigoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Cliente.ServiciosGestionUsuarios.SolicitudAmigo[] SolicitudAmigo {
            get {
                return this.SolicitudAmigoField;
            }
            set {
                if ((object.ReferenceEquals(this.SolicitudAmigoField, value) != true)) {
                    this.SolicitudAmigoField = value;
                    this.RaisePropertyChanged("SolicitudAmigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string claveUsuarioAmigo {
            get {
                return this.claveUsuarioAmigoField;
            }
            set {
                if ((object.ReferenceEquals(this.claveUsuarioAmigoField, value) != true)) {
                    this.claveUsuarioAmigoField = value;
                    this.RaisePropertyChanged("claveUsuarioAmigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idAmigo {
            get {
                return this.idAmigoField;
            }
            set {
                if ((this.idAmigoField.Equals(value) != true)) {
                    this.idAmigoField = value;
                    this.RaisePropertyChanged("idAmigo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Bloqueado", Namespace="http://schemas.datacontract.org/2004/07/AccesoDatos")]
    [System.SerializableAttribute()]
    public partial class Bloqueado : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Cliente.ServiciosGestionUsuarios.SolicitudBloqueo[] SolicitudBloqueoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string claveJugadorBloqueadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idBloqueoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Cliente.ServiciosGestionUsuarios.SolicitudBloqueo[] SolicitudBloqueo {
            get {
                return this.SolicitudBloqueoField;
            }
            set {
                if ((object.ReferenceEquals(this.SolicitudBloqueoField, value) != true)) {
                    this.SolicitudBloqueoField = value;
                    this.RaisePropertyChanged("SolicitudBloqueo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string claveJugadorBloqueado {
            get {
                return this.claveJugadorBloqueadoField;
            }
            set {
                if ((object.ReferenceEquals(this.claveJugadorBloqueadoField, value) != true)) {
                    this.claveJugadorBloqueadoField = value;
                    this.RaisePropertyChanged("claveJugadorBloqueado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idBloqueo {
            get {
                return this.idBloqueoField;
            }
            set {
                if ((this.idBloqueoField.Equals(value) != true)) {
                    this.idBloqueoField = value;
                    this.RaisePropertyChanged("idBloqueo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Perfil", Namespace="http://schemas.datacontract.org/2004/07/Servicios.Interfaces")]
    [System.SerializableAttribute()]
    public partial class Perfil : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] FotoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreUsuarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Foto {
            get {
                return this.FotoField;
            }
            set {
                if ((object.ReferenceEquals(this.FotoField, value) != true)) {
                    this.FotoField = value;
                    this.RaisePropertyChanged("Foto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreUsuario {
            get {
                return this.NombreUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreUsuarioField, value) != true)) {
                    this.NombreUsuarioField = value;
                    this.RaisePropertyChanged("NombreUsuario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiciosGestionUsuarios.IServicioRegistrarUsuario")]
    public interface IServicioRegistrarUsuario {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioRegistrarUsuario/EnviarCodigoCorreo", ReplyAction="http://tempuri.org/IServicioRegistrarUsuario/EnviarCodigoCorreoResponse")]
        string EnviarCodigoCorreo(string correo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioRegistrarUsuario/EnviarCodigoCorreo", ReplyAction="http://tempuri.org/IServicioRegistrarUsuario/EnviarCodigoCorreoResponse")]
        System.Threading.Tasks.Task<string> EnviarCodigoCorreoAsync(string correo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioRegistrarUsuario/RegistrarUsuario", ReplyAction="http://tempuri.org/IServicioRegistrarUsuario/RegistrarUsuarioResponse")]
        bool RegistrarUsuario(Cliente.ServiciosGestionUsuarios.Usuario usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioRegistrarUsuario/RegistrarUsuario", ReplyAction="http://tempuri.org/IServicioRegistrarUsuario/RegistrarUsuarioResponse")]
        System.Threading.Tasks.Task<bool> RegistrarUsuarioAsync(Cliente.ServiciosGestionUsuarios.Usuario usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioRegistrarUsuario/ValidarNombreNoRepetido", ReplyAction="http://tempuri.org/IServicioRegistrarUsuario/ValidarNombreNoRepetidoResponse")]
        bool ValidarNombreNoRepetido(string nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioRegistrarUsuario/ValidarNombreNoRepetido", ReplyAction="http://tempuri.org/IServicioRegistrarUsuario/ValidarNombreNoRepetidoResponse")]
        System.Threading.Tasks.Task<bool> ValidarNombreNoRepetidoAsync(string nombre);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioRegistrarUsuarioChannel : Cliente.ServiciosGestionUsuarios.IServicioRegistrarUsuario, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioRegistrarUsuarioClient : System.ServiceModel.ClientBase<Cliente.ServiciosGestionUsuarios.IServicioRegistrarUsuario>, Cliente.ServiciosGestionUsuarios.IServicioRegistrarUsuario {
        
        public ServicioRegistrarUsuarioClient() {
        }
        
        public ServicioRegistrarUsuarioClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioRegistrarUsuarioClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioRegistrarUsuarioClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioRegistrarUsuarioClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string EnviarCodigoCorreo(string correo) {
            return base.Channel.EnviarCodigoCorreo(correo);
        }
        
        public System.Threading.Tasks.Task<string> EnviarCodigoCorreoAsync(string correo) {
            return base.Channel.EnviarCodigoCorreoAsync(correo);
        }
        
        public bool RegistrarUsuario(Cliente.ServiciosGestionUsuarios.Usuario usuario) {
            return base.Channel.RegistrarUsuario(usuario);
        }
        
        public System.Threading.Tasks.Task<bool> RegistrarUsuarioAsync(Cliente.ServiciosGestionUsuarios.Usuario usuario) {
            return base.Channel.RegistrarUsuarioAsync(usuario);
        }
        
        public bool ValidarNombreNoRepetido(string nombre) {
            return base.Channel.ValidarNombreNoRepetido(nombre);
        }
        
        public System.Threading.Tasks.Task<bool> ValidarNombreNoRepetidoAsync(string nombre) {
            return base.Channel.ValidarNombreNoRepetidoAsync(nombre);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiciosGestionUsuarios.IServicioLogin")]
    public interface IServicioLogin {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioLogin/Login", ReplyAction="http://tempuri.org/IServicioLogin/LoginResponse")]
        Cliente.ServiciosGestionUsuarios.Jugador Login(string nombreUsuario, string contrasenia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioLogin/Login", ReplyAction="http://tempuri.org/IServicioLogin/LoginResponse")]
        System.Threading.Tasks.Task<Cliente.ServiciosGestionUsuarios.Jugador> LoginAsync(string nombreUsuario, string contrasenia);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioLoginChannel : Cliente.ServiciosGestionUsuarios.IServicioLogin, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioLoginClient : System.ServiceModel.ClientBase<Cliente.ServiciosGestionUsuarios.IServicioLogin>, Cliente.ServiciosGestionUsuarios.IServicioLogin {
        
        public ServicioLoginClient() {
        }
        
        public ServicioLoginClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioLoginClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioLoginClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioLoginClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Cliente.ServiciosGestionUsuarios.Jugador Login(string nombreUsuario, string contrasenia) {
            return base.Channel.Login(nombreUsuario, contrasenia);
        }
        
        public System.Threading.Tasks.Task<Cliente.ServiciosGestionUsuarios.Jugador> LoginAsync(string nombreUsuario, string contrasenia) {
            return base.Channel.LoginAsync(nombreUsuario, contrasenia);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiciosGestionUsuarios.IServicioPersonalizarPerfil")]
    public interface IServicioPersonalizarPerfil {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPersonalizarPerfil/GuardarCambios", ReplyAction="http://tempuri.org/IServicioPersonalizarPerfil/GuardarCambiosResponse")]
        bool GuardarCambios(Cliente.ServiciosGestionUsuarios.Perfil perfil, string claveUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPersonalizarPerfil/GuardarCambios", ReplyAction="http://tempuri.org/IServicioPersonalizarPerfil/GuardarCambiosResponse")]
        System.Threading.Tasks.Task<bool> GuardarCambiosAsync(Cliente.ServiciosGestionUsuarios.Perfil perfil, string claveUsuario);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioPersonalizarPerfilChannel : Cliente.ServiciosGestionUsuarios.IServicioPersonalizarPerfil, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioPersonalizarPerfilClient : System.ServiceModel.ClientBase<Cliente.ServiciosGestionUsuarios.IServicioPersonalizarPerfil>, Cliente.ServiciosGestionUsuarios.IServicioPersonalizarPerfil {
        
        public ServicioPersonalizarPerfilClient() {
        }
        
        public ServicioPersonalizarPerfilClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioPersonalizarPerfilClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioPersonalizarPerfilClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioPersonalizarPerfilClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool GuardarCambios(Cliente.ServiciosGestionUsuarios.Perfil perfil, string claveUsuario) {
            return base.Channel.GuardarCambios(perfil, claveUsuario);
        }
        
        public System.Threading.Tasks.Task<bool> GuardarCambiosAsync(Cliente.ServiciosGestionUsuarios.Perfil perfil, string claveUsuario) {
            return base.Channel.GuardarCambiosAsync(perfil, claveUsuario);
        }
    }
}
