//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatosJugadorPartida
    {
        public Nullable<int> puntaje { get; set; }
        public Nullable<int> idAspecto { get; set; }
        public Nullable<bool> explusado { get; set; }
        public int idDatosJugadorPartida { get; set; }
        public Nullable<bool> expulsado { get; set; }
    }
}
