//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatosJugadorPartida
    {
        public Nullable<int> puntaje { get; set; }
        public Nullable<int> idAspecto { get; set; }
        public int idDatosJugadorPartida { get; set; }
        public Nullable<bool> expulsado { get; set; }
        public int idJugador { get; set; }
        public int idPartida { get; set; }
        public Nullable<bool> esAdmin { get; set; }
        public string claveJugador { get; set; }
        public string clavePartida { get; set; }
    
        public virtual Jugador Jugador { get; set; }
        public virtual Partida Partida { get; set; }
    }
}
