//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jugador
    {
        public string descripcion { get; set; }
        public byte[] fotoPerfil { get; set; }
        public string correoElectronico { get; set; }
        public string claveUsuario { get; set; }
        public string contrasenia { get; set; }
        public string estado { get; set; }
        public string nombreUsuario { get; set; }
        public Nullable<bool> esInvitado { get; set; }
        public int idJugador { get; set; }
    }
}
