//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jugador
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Jugador()
        {
            this.DatosJugadorPartida = new HashSet<DatosJugadorPartida>();
            this.SolicitudAmigo = new HashSet<SolicitudAmigo>();
        }
    
        public string descripcion { get; set; }
        public byte[] fotoPerfil { get; set; }
        public string correoElectronico { get; set; }
        public string claveUsuario { get; set; }
        public string contrasenia { get; set; }
        public string estado { get; set; }
        public string nombreUsuario { get; set; }
        public Nullable<bool> esInvitado { get; set; }
        public int idJugador { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DatosJugadorPartida> DatosJugadorPartida { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SolicitudAmigo> SolicitudAmigo { get; set; }
    }
}
