//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jugador
    {
        public string descripcion { get; set; }
        public byte[] fotoPerfil { get; set; }
        public string correoElectronico { get; set; }
        public string claveUsuario { get; set; }
        public string contrasenia { get; set; }
        public string estado { get; set; }
        public string nombreUsuario { get; set; }
        public Nullable<bool> esInvitado { get; set; }
        public int idJugador { get; set; }
    }
}
