//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partida
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Partida()
        {
            this.DatosJugadorPartida = new HashSet<DatosJugadorPartida>();
        }
    
        public string estado { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<int> duracion { get; set; }
        public string codigoPartida { get; set; }
        public Nullable<int> tiempoGuerra { get; set; }
        public Nullable<int> puntajeVictoria { get; set; }
        public string nombreGanador { get; set; }
        public int idPartida { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DatosJugadorPartida> DatosJugadorPartida { get; set; }
    }
}
