//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partida
    {
        public string estado { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<int> duracion { get; set; }
        public string codigoPartida { get; set; }
        public Nullable<int> tiempoGuerra { get; set; }
        public Nullable<int> puntajeVictoria { get; set; }
        public string nombreGanador { get; set; }
        public int idPartida { get; set; }
    }
}
