//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class SolicitudAmigo
    {
        public Nullable<System.DateTime> fecha { get; set; }
        public string estado { get; set; }
        public int idSolicitudAmigo { get; set; }
        public int idAmigo { get; set; }
        public int idJugador { get; set; }
    
        public virtual Jugador Jugador { get; set; }
        public virtual Amigo Amigo { get; set; }
    }
}
