//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cliente.ServicioPersonalizarPerfil {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Perfil", Namespace="http://schemas.datacontract.org/2004/07/Servicios")]
    [System.SerializableAttribute()]
    public partial class Perfil : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] FotoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreUsuarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Foto {
            get {
                return this.FotoField;
            }
            set {
                if ((object.ReferenceEquals(this.FotoField, value) != true)) {
                    this.FotoField = value;
                    this.RaisePropertyChanged("Foto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreUsuario {
            get {
                return this.NombreUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreUsuarioField, value) != true)) {
                    this.NombreUsuarioField = value;
                    this.RaisePropertyChanged("NombreUsuario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioPersonalizarPerfil.IServicioPersonalizarPerfil")]
    public interface IServicioPersonalizarPerfil {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPersonalizarPerfil/GuardarCambios", ReplyAction="http://tempuri.org/IServicioPersonalizarPerfil/GuardarCambiosResponse")]
        bool GuardarCambios(Cliente.ServicioPersonalizarPerfil.Perfil perfil, string claveUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPersonalizarPerfil/GuardarCambios", ReplyAction="http://tempuri.org/IServicioPersonalizarPerfil/GuardarCambiosResponse")]
        System.Threading.Tasks.Task<bool> GuardarCambiosAsync(Cliente.ServicioPersonalizarPerfil.Perfil perfil, string claveUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPersonalizarPerfil/ObtenerPerfil", ReplyAction="http://tempuri.org/IServicioPersonalizarPerfil/ObtenerPerfilResponse")]
        Cliente.ServicioPersonalizarPerfil.Perfil ObtenerPerfil(string claveUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPersonalizarPerfil/ObtenerPerfil", ReplyAction="http://tempuri.org/IServicioPersonalizarPerfil/ObtenerPerfilResponse")]
        System.Threading.Tasks.Task<Cliente.ServicioPersonalizarPerfil.Perfil> ObtenerPerfilAsync(string claveUsuario);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioPersonalizarPerfilChannel : Cliente.ServicioPersonalizarPerfil.IServicioPersonalizarPerfil, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioPersonalizarPerfilClient : System.ServiceModel.ClientBase<Cliente.ServicioPersonalizarPerfil.IServicioPersonalizarPerfil>, Cliente.ServicioPersonalizarPerfil.IServicioPersonalizarPerfil {
        
        public ServicioPersonalizarPerfilClient() {
        }
        
        public ServicioPersonalizarPerfilClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioPersonalizarPerfilClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioPersonalizarPerfilClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioPersonalizarPerfilClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool GuardarCambios(Cliente.ServicioPersonalizarPerfil.Perfil perfil, string claveUsuario) {
            return base.Channel.GuardarCambios(perfil, claveUsuario);
        }
        
        public System.Threading.Tasks.Task<bool> GuardarCambiosAsync(Cliente.ServicioPersonalizarPerfil.Perfil perfil, string claveUsuario) {
            return base.Channel.GuardarCambiosAsync(perfil, claveUsuario);
        }
        
        public Cliente.ServicioPersonalizarPerfil.Perfil ObtenerPerfil(string claveUsuario) {
            return base.Channel.ObtenerPerfil(claveUsuario);
        }
        
        public System.Threading.Tasks.Task<Cliente.ServicioPersonalizarPerfil.Perfil> ObtenerPerfilAsync(string claveUsuario) {
            return base.Channel.ObtenerPerfilAsync(claveUsuario);
        }
    }
}
